# Generated by Django 5.2.3 on 2025-07-03 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesgiven',
            name='salonAppointmentId',
        ),
        migrations.RemoveField(
            model_name='servicesgiven',
            name='servicesGiven',
        ),
        migrations.RemoveField(
            model_name='servicesgiven',
            name='customerId',
        ),
        migrations.RemoveField(
            model_name='servicesgiven',
            name='employeeId',
        ),
        migrations.DeleteModel(
            name='salonAppointment',
        ),
    ]
