# Generated by Django 5.2.3 on 2025-07-03 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_servicesgiven_salonappointmentid_and_more'),
        ('users', '0002_remove_customerprofile_user_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='services',
        ),
        migrations.DeleteModel(
            name='servicesGiven',
        ),
    ]
