# Generated by Django 5.2.3 on 2025-07-03 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0005_initial'),
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonappointment',
            name='customerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customerprofile'),
        ),
        migrations.AddField(
            model_name='salonappointment',
            name='employeeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employeeprofile'),
        ),
        migrations.AddField(
            model_name='salonappointment',
            name='serviceId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.services'),
        ),
        migrations.AddField(
            model_name='servicesgiven',
            name='customerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customerprofile'),
        ),
        migrations.AddField(
            model_name='servicesgiven',
            name='employeeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employeeprofile'),
        ),
        migrations.AddField(
            model_name='servicesgiven',
            name='salonAppointmentId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.salonappointment'),
        ),
        migrations.AddField(
            model_name='servicesgiven',
            name='servicesGiven',
            field=models.ManyToManyField(to='services.services'),
        ),
    ]
