# Generated by Django 5.2.3 on 2025-07-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0008_delete_services_delete_servicesgiven'),
    ]

    operations = [
        migrations.CreateModel(
            name='salonAppointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scheduleDay', models.DateField()),
                ('appointmentStatus', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=25)),
                ('serviceName', models.CharField(max_length=25)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=100)),
                ('durationOfService', models.CharField(max_length=20)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='servicesGiven',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customerRating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=20)),
                ('customerComment', models.TextField()),
                ('employeeRating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=20)),
                ('employeeComment', models.TextField()),
            ],
        ),
    ]
