# Generated by Django 5.2.3 on 2025-07-04 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salon', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonappointment',
            name='customerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customerprofile'),
        ),
        migrations.AddField(
            model_name='salonappointment',
            name='employeeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employeeprofile'),
        ),
        migrations.AddField(
            model_name='salonappointment',
            name='serviceId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salon.services'),
        ),
        migrations.AddField(
            model_name='servicesgiven',
            name='customerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customerprofile'),
        ),
        migrations.AddField(
            model_name='servicesgiven',
            name='employeeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employeeprofile'),
        ),
        migrations.AddField(
            model_name='servicesgiven',
            name='salonAppointmentId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salon.salonappointment'),
        ),
        migrations.AddField(
            model_name='servicesgiven',
            name='servicesGiven',
            field=models.ManyToManyField(to='salon.services'),
        ),
    ]
