# Generated by Django 5.2.3 on 2025-07-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesgiven',
            name='customerRating',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1),
        ),
        migrations.AlterField(
            model_name='servicesgiven',
            name='employeeRating',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1),
        ),
    ]
