# Generated by Django 5.2.3 on 2025-07-05 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_alter_servicesgiven_customerrating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesgiven',
            name='salonAppointmentId',
        ),
        migrations.RemoveField(
            model_name='servicesgiven',
            name='servicesGiven',
        ),
        migrations.RemoveField(
            model_name='servicesgiven',
            name='customerId',
        ),
        migrations.RemoveField(
            model_name='servicesgiven',
            name='employeeId',
        ),
        migrations.DeleteModel(
            name='salonAppointment',
        ),
    ]
