# Generated by Django 5.2.3 on 2025-07-06 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salon', '0006_initial'),
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonappointment',
            name='customerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customerprofile'),
        ),
        migrations.AddField(
            model_name='salonappointment',
            name='employeeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employeeprofile'),
        ),
        migrations.AddField(
            model_name='salonappointment',
            name='services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.service', to_field='serviceName'),
        ),
        migrations.AddField(
            model_name='servicesgiven',
            name='customerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customerprofile'),
        ),
        migrations.AddField(
            model_name='servicesgiven',
            name='employeeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employeeprofile'),
        ),
        migrations.AddField(
            model_name='servicesgiven',
            name='salonAppointmentId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salon.salonappointment'),
        ),
        migrations.AddField(
            model_name='servicesgiven',
            name='servicesId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.service'),
        ),
    ]
