# Generated by Django 5.2.3 on 2025-07-06 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0007_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='serviceName',
            new_name='service_name',
        ),
    ]
