# Generated by Django 5.2.3 on 2025-07-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0008_rename_servicename_service_service_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salonappointment',
            name='services',
        ),
        migrations.AddField(
            model_name='salonappointment',
            name='services',
            field=models.ManyToManyField(related_name='salon_appointment', to='salon.service'),
        ),
    ]
