# Generated by Django 5.2.3 on 2025-07-13 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0009_remove_salonappointment_services_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salonappointment',
            name='services',
        ),
        migrations.AddField(
            model_name='salonappointment',
            name='services',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='salon_appointment', to='salon.service'),
            preserve_default=False,
        ),
    ]
