# Generated by Django 5.2.3 on 2025-07-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0010_remove_salonappointment_services_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salonappointment',
            name='services',
        ),
        migrations.AddField(
            model_name='salonappointment',
            name='services',
            field=models.ManyToManyField(related_name='salon_appointment', to='salon.service'),
        ),
    ]
