# Generated by Django 5.2.3 on 2025-07-17 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0012_remove_servicesgiven_salonappointmentid_and_more'),
        ('users', '0009_remove_customerprofile_user_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='service',
        ),
        migrations.DeleteModel(
            name='servicesGiven',
        ),
    ]
