# Generated by Django 5.2.3 on 2025-07-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salon', '0013_delete_service_delete_servicesgiven'),
    ]

    operations = [
        migrations.CreateModel(
            name='salonAppointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scheduleDay', models.DateField()),
                ('appointmentStatus', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=25)),
                ('service_name', models.CharField(max_length=25, unique=True)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=400)),
                ('durationOfService', models.CharField(max_length=20)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'services',
            },
        ),
        migrations.CreateModel(
            name='servicesGiven',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customerRating', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')])),
                ('customerComment', models.TextField(max_length=200)),
                ('employeeRating', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')])),
                ('employeeComment', models.TextField(max_length=200)),
            ],
        ),
    ]
