# Generated by Django 5.2.3 on 2025-07-18 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0015_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesgiven',
            name='salonAppointmentId',
        ),
        migrations.RemoveField(
            model_name='servicesgiven',
            name='servicesId',
        ),
        migrations.RemoveField(
            model_name='servicesgiven',
            name='customerId',
        ),
        migrations.RemoveField(
            model_name='servicesgiven',
            name='employeeId',
        ),
        migrations.DeleteModel(
            name='salonAppointment',
        ),
    ]
