# Generated by Django 5.2.3 on 2025-07-26 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0019_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salonappointment',
            old_name='endTime',
            new_name='appointmentEndTime',
        ),
        migrations.RenameField(
            model_name='salonappointment',
            old_name='startTime',
            new_name='appointmentTime',
        ),
    ]
