# Generated by Django 5.2.3 on 2025-08-11 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0020_rename_endtime_salonappointment_appointmentendtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salonappointment',
            name='appointmentStatus',
        ),
    ]
