# Generated by Django 5.2.3 on 2025-09-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0021_remove_salonappointment_appointmentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='new_durationOfService',
            field=models.DurationField(null=True),
        ),
    ]
