# Generated by Django 5.2.3 on 2025-09-06 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0023_auto_20250905_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='durationOfService',
        ),
    ]
