# Generated by Django 5.2.3 on 2025-09-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0024_remove_service_durationofservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonappointment',
            name='total_price',
            field=models.IntegerField(null=True),
        ),
    ]
