# Generated by Django 5.2.3 on 2025-10-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0026_alter_servicesgiven_customerrating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesgiven',
            name='customerComment',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicesgiven',
            name='customerRating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AlterField(
            model_name='servicesgiven',
            name='employeeComment',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicesgiven',
            name='employeeRating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
