# Generated by Django 5.2.3 on 2025-07-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0008_rename_servicename_service_service_name'),
        ('users', '0005_alter_customuser_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='services_offered',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='services_offered',
            field=models.ManyToManyField(related_name='employee_profile', to='salon.service', verbose_name='services offered'),
        ),
    ]
