# Generated by Django 5.2.3 on 2025-07-15 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_employeeprofile_services_offered_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='services_offered',
            new_name='services_to_offer',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='skills',
        ),
    ]
