# Generated by Django 5.2.3 on 2025-07-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_services_offered_employeeprofile_services_to_offer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('CUSTOMER', 'Customer')], max_length=20, verbose_name='user role'),
        ),
    ]
