# Generated by Django 5.2.3 on 2025-07-17 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0012_remove_servicesgiven_salonappointmentid_and_more'),
        ('users', '0008_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='services_to_offer',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='adminProfile',
        ),
        migrations.DeleteModel(
            name='customerProfile',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='employeeProfile',
        ),
    ]
