# Generated by Django 5.2.3 on 2025-07-18 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0016_remove_servicesgiven_salonappointmentid_and_more'),
        ('users', '0010_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='services_to_offer',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='AdminProfile',
        ),
        migrations.DeleteModel(
            name='CustomerProfile',
        ),
        migrations.DeleteModel(
            name='EmployeeProfile',
        ),
    ]
