# Generated by Django 5.2.3 on 2025-07-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0019_initial'),
        ('users', '0012_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='services_to_offer',
            field=models.ManyToManyField(related_name='employee_profile', to='salon.service', verbose_name='services to offer'),
        ),
    ]
